version: '3.8'

# Services disponibles :
# - frontend: Frontend sur le port 3001
# - api-js: API JavaScript sur le port 3000
# - api-python: API Python sur le port 3000
# - api-java: API Java sur le port 3000

services:
  # --- SERVICES FRONTEND ---
  frontend:
    build:
      context: Calculator
      dockerfile: Dockerfile
    container_name: calculator-frontend
    ports:
      - "3001:3001"
    environment:
      - CI=false
    cpus: 4
    mem_limit: 2g
    tty: true

  # --- SERVICES API JAVASCRIPT ---
  api-js:
    build:
      context: calculator-api-js
      dockerfile: Dockerfile
    container_name: calculator-api-js
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: sh -c "npm run lint && npm test && npm start"
    volumes:
      - ./calculator-api-js:/app
      - /app/node_modules

  # --- SERVICES API PYTHON ---
  api-python:
    build:
      context: calculator-api-python
      dockerfile: Dockerfile
    container_name: calculator-api-python
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  # --- SERVICES API JAVA ---
  api-java:
    build:
      context: calculator-api-java
      dockerfile: Dockerfile
    container_name: calculator-api-java
    ports:
      - "3000:3000"
